#!/usr/bin/env python3
"""
List all databases in MongoDB.
"""

from pymongo import MongoClient


def list_databases():
    try:
        # Connect to MongoDB
        client = MongoClient("mongodb://localhost:27017")

        # List all databases
        databases = client.list_database_names()
        for db in databases:
            print(db)
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        client.close()


if __name__ == "__main__":
    list_databases()
