#!/usr/bin/env python3

import pymongo


def list_databases():
    try:
        # Connect to the MongoDB server
        client = pymongo.MongoClient("mongodb://localhost:27017")

        # List all available databases
        database_list = client.list_database_names()

        # Print the list of databases
        for db in database_list:
            print(db)

    except Exception as e:
        print("An error occurred:", str(e))


if __name__ == "__main__":
    list_databases()
